#!/usr/bin/env python
"""Node for measuring the pose error with respect to the KITTI odometry sequences' ground truth"""

import rospy

from panoptic_slam.kitti.nodes import KittiGTPoseError

if __name__ == "__main__":
    rospy.init_node("kitti_gt_labeler")

    kitti_dir = rospy.get_param("kitti_dataset_path")
    kitti_seq = rospy.get_param("kitti_sequence")

    output_dir = rospy.get_param("~output_dir")

    node = KittiGTPoseError(kitti_dir, kitti_seq, output_dir)

    rospy.spin()
