#!/usr/bin/env python
"""Node for publishing the panoptic labels of the KITTI odometry sequences' ground truth"""

import rospy

from panoptic_slam.kitti.nodes import KittiGTPanopticLabeler

if __name__ == "__main__":
    rospy.init_node("kitti_gt_labeler")

    kitti_dir = rospy.get_param("kitti_dataset_path")
    kitti_seq = rospy.get_param("kitti_sequence")

    node = KittiGTPanopticLabeler(kitti_dir, kitti_seq)

    rospy.spin()
